#!/bin/bash

time=`date`
echo [${time}] PWM script started, push to 80% for 3 seconds to start
echo 0 > /sys/devices/platform/fd8b0010.pwm/pwm/pwmchip*/export
echo 10000 > /sys/devices/platform/fd8b0010.pwm/pwm/pwmchip*/pwm0/period
echo 8000 > /sys/devices/platform/fd8b0010.pwm/pwm/pwmchip*/pwm0/duty_cycle
echo normal > /sys/devices/platform/fd8b0010.pwm/pwm/pwmchip*/pwm0/polarity
echo 1 > /sys/devices/platform/fd8b0010.pwm/pwm/pwmchip*/pwm0/enable
sleep 3

while true
do
	temp=`cat /sys/class/thermal/thermal_zone0/temp`
	time=`date`
	pwm=`echo ${temp} | awk '{printf("%d",$1*0.15-800)}'`
    temp=`echo ${temp} | awk '{printf("%d",$1/1000)}'`
	if (( $pwm > 8500 ))
	then
		pwm=8500
	elif (( $pwm < 5000 ))
	then
		pwm=5000
	fi
	echo ${pwm} > /sys/devices/platform/fd8b0010.pwm/pwm/pwmchip*/pwm0/duty_cycle
	echo [${time}] Thermal value: ${temp}C°, write fan PWM cycle ${pwm}
	sleep 5
done